// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktdfggumbuphcegbrsxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0ZGZnZ3VtYnVwaGNlZ2Jyc3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTk2MDQsImV4cCI6MjA2NDM3NTYwNH0.HgOzDfN7_ystx-4XG-A4wRTeYfJ88N_3ZC8BrZcxlVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);